git rm  btest
 git rm  cloud/3rd-party/vitest.config.ts
 git rm  cloud/3rd-party/x
 git rm  cloud/box-party/index.html
 git rm  cloud/box-party/package.json
 git rm  cloud/box-party/public/vite.svg
 git rm  cloud/box-party/src/Box.css
 git rm  cloud/box-party/src/Box.tsx
 git rm  cloud/box-party/src/assets/react.svg
 git rm  cloud/box-party/src/index.css
 git rm  cloud/box-party/src/main.tsx
 git rm  cloud/box-party/src/overlayHtml.tsx
 git rm  cloud/box-party/src/vite-env.d.ts
 git rm  cloud/box-party/tsconfig.json
 git rm  cloud/box-party/vite.config.ts
 git rm  cloud/connector/svc/svc-fpcc-protocol.ts
 git rm  dashboard/frontend/x
 git rm  dashboard/x
 git rm  deno.lock
 git rm  jwt
 git rm  out.2.6.6
 git rm  out.2.6.7
 git rm  playwright-chrome/.dockerignore
 git rm  playwright-chrome/.gitignore
 git rm  playwright-chrome/Dockerfile
 git rm  playwright-chrome/README.md
 git rm  playwright-chrome/deploy.sh
 git rm  playwright-chrome/package-lock.json
 git rm  playwright-chrome/package.json
 git rm  playwright-chrome/src/index.ts
 git rm  playwright-chrome/test-event.json
 git rm  playwright-chrome/tsconfig.json
 git rm  retry-connection
 git rm  rslint.jsonc
 git rm  scripts/Dockerfile
 git rm  scripts/cnpm-test/Dockerfile
 git rm  scripts/cnpm-test/README.md
 git rm  scripts/cnpm-test/config.json
 git rm  scripts/cnpm-test/docker-compose.yml
 git rm  scripts/x
 git rm  set
 git rm  should
 git rm  test-plimit
 git rm  vendor/level/abstract-level/test/self/iterator-test.ts:1
 git rm  x
