name: "setup-runtime"
description: "setup  runtime"
# inputs:
# your inputs here
runs:
  using: composite
  steps:
    - uses: ./actions/runtime

    - name: install
      shell: bash
      run: |
        pnpm remove -r playwright-chromium
        pnpm install

    - name: format-check
      shell: bash
      run: pnpm run format --check

    - name: lint
      shell: bash
      run: pnpm run lint

    - name: build
      shell: bash
      run: pnpm run build

    - name: playwright
      shell: bash
      run: |
        pnpm exec playwright install --with-deps chromium
        pnpm exec playwright --version

    - name: test
      shell: bash
      env:
        FP_CI: fp_ci
      run: pnpm exec core-cli retry -- pnpm run test

    - name: test:deno
      shell: bash
      env:
        FP_CI: fp_ci
      run: pnpm exec core-cli retry -- pnpm run test:deno

    - name: start-esm + npm
      shell: bash
      env:
        FP_CI: fp_ci
      run: |
        bash smoke/setup-local-esm-npm.sh
        #cp ./dist/npmrc-smoke .npmrc

    - name: smoke
      shell: bash
      env:
        FP_CI: fp_ci
      run: pnpm exec core-cli retry -- pnpm run smoke
