name: "@fireproof/core-publish"
description: "setup  runtime"
inputs:
  NPM_TOKEN:
    description: "NPM token for publishing packages"
    required: true
# your inputs here
runs:
  using: "composite"
  steps:
    - name: publish
      shell: bash
      run: |
        rm -f ~/.npmrc $(find . -name .npmrc -o -name npmrc-smoke -print)
        npm install -g npm@11
        npm --version
        git fetch --tags --force > /dev/null
        git config --local --add gpg.ssh.allowedSignersFile ./allowed_signers
        echo "GITHUB_REF->"$GITHUB_REF
        git tag -v $(git describe --tags --abbrev=0)
        pnpm run publish --registry https://registry.npmjs.org/
