services:
  registry:
    image: "verdaccio/verdaccio"
    #volumes:
    #  - ./verdaccio.config.yaml:/verdaccio/conf/config.yaml
    ports:
      - "4873:4873"
    # docker run -p 4873:4873 -v $(pwd)/verdaccio.config.yaml:/verdaccio/conf/config.yaml -ti verdaccio/verdaccio
  esm-sh:
    image: "ghcr.io/esm-dev/esm.sh"
    environment:
      NPM_REGISTRY: http://registry:4873/
    ports:
      - "4874:8080"
#   wait-for-ready:
#     image: curlimages/curl
#     command: "sleep 86400"
#     depends_on:
#       registry:
#         condition: service_started
#       esm-sh:
#         condition: service_started
#     healthcheck:
#       test:
#         - CMD-SHELL
#         - "-c"
#         - "curl http://registry:4873 && curl http://esm-sh:4874"
#       interval: 5s
#       retries: 30
#       timeout: 2s
