name: "@fireproof/core - CI - base"

on:
  workflow_call:
    # inputs:
    #   environment:
    #     required: true
    #     type: string
    # secrets:
    #   token:
    #     required: true

env:
  FP_CI: "fp_ci"
  GIT_DISCOVERY_ACROSS_FILESYSTEM: "true"

jobs:
  pre-build:
    timeout-minutes: 10
    name: pre-build
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 10

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      #- uses: actions/setup-node@v4
      #  with:
      #    node-version: 20
      #    cache: pnpm

      # - uses: denoland/setup-deno@v2
      #   with:
      #     deno-version: v2.x

      # - name: Sticky-disk-node_modules
      #   uses: useblacksmith/stickydisk@v1
      #   with:
      #     key: ${{ github.repository }}-${{ github.ref }}-node_modules
      #     path: ./node_modules

      #- name: Sticky-disk-cache
      #  uses: useblacksmith/stickydisk@v1
      #  with:
      #    key: ${{ github.repository }}-cache
      #    path: ~/.cache

      # - name: smoke-esm-cache
      #   id: smoke-esm-cache
      #   uses: useblacksmith/cache@v5
      #   with:
      #     path: ~/.cache
      #     key: smoke-esm-cache

      # - name: start-esm + npm
      #   run: |
      #     bash .github/workflows/setup-local-esm-npm.sh
      #     cp ./dist/npmrc-smoke .npmrc

      - name: install
        run: pnpm install
      - name: format-check
        run: pnpm run format --check
      - name: lint
        run: pnpm run lint

      # - name: Upload node_modules
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: node_modules
      #     path: node_modules/

  build:
    name: build
    needs: pre-build
    runs-on: blacksmith-2vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 10

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: install
        run: pnpm install

      #- name: Sticky-disk-dist
      # uses: useblacksmith/stickydisk@v1
      # with:
      #   key: ${{ github.repository }}-${{ github.ref }}-dist
      #   path: ./dist

      - name: build
        run: pnpm run build

  test-node:
    timeout-minutes: 3
    name: test-node
    needs: pre-build
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      #- name: Sticky-disk-cache
      #  uses: useblacksmith/stickydisk@v1
      #  with:
      #    key: ${{ github.repository }}-cache
      #    path: ~/.cache

      - name: install
        run: pnpm install

      - name: playwright
        run: pnpm exec playwright install chromium

      - name: test Attempt 1
        id: attempt1
        continue-on-error: true
        run: pnpm run test

      - name: test Attempt 2
        if: steps.attempt1.outcome == 'failure'
        run: pnpm run test

      #- uses: denoland/setup-deno@v2
      #  with:
      #    deno-version: v2.x

      - name: test:deno 1
        id: denoattempt1
        run: pnpm run test:deno
        continue-on-error: true

      - name: test:deno 2
        id: denoattempt2
        if: steps.denoattempt1.outcome == 'failure'
        run: pnpm run test:deno

  smoke:
    timeout-minutes: 4
    name: smoke
    needs: ["test-node", "build"]
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      #- uses: denoland/setup-deno@v2
      #  with:
      #    deno-version: v2.x

      - name: install
        run: pnpm install

      #- name: Sticky-disk-cache
      #  uses: useblacksmith/stickydisk@v1
      #  with:
      #    key: ${{ github.repository }}-cache
      #    path: ~/.cache

      #- name: Sticky-disk-dist
      #  uses: useblacksmith/stickydisk@v1
      #  with:
      #    key: ${{ github.repository }}-${{ github.ref }}-dist
      #    path: ./dist

      - name: playwright
        run: pnpm exec playwright install chromium

      - name: start-esm + npm
        run: |
          bash .github/workflows/setup-local-esm-npm.sh
          cp ./dist/npmrc-smoke .npmrc

      - name: smoke Attempt 1
        id: attempt1
        continue-on-error: true
        run: pnpm run smoke

      - name: smoke Attempt 2
        if: steps.attempt1.outcome == 'failure'
        run: pnpm run smoke-retry

  # clean-sticky-cache:
  #   name: clean-sticky-cache
  #   runs-on: blacksmith-2vcpu-ubuntu-2204
  #   needs: [build, test-node, smoke, publish, cf-deploy]
  #   if: always()
  #   steps:
  #     - name: Sticky-disk-dist
  #       uses: useblacksmith/stickydisk@v1
  #       with:
  #         key: ${{ github.repository }}-${{ github.ref }}-dist
  #         path: ./dist
  #     - name: wipe-sticky-cache
  #       run: |
  #         (cd dist && rm -rf $(ls -A) || true)
