name: '@fireproof/core - CI - base'

on:
  workflow_call:

jobs:
  setup-runtime:
    name: pre-build
    runs-on: blacksmith-4vcpu-ubuntu-2204
    steps:
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
          version: 10

      - uses: useblacksmith/setup-node@v5
        with:
          node-version: 22
          cache: pnpm
